const JobList = [
  {
    id: '1',
    title: 'UI/UX Designer',
    company: 'Barone LLC.',
    type: 'Remote',
    salary: '$200-$800',
    logo: '/src/assets/Amazon.svg',
    description: 'Design user-friendly interfaces and create visually appealing designs for web and mobile applications. Collaborate with developers to ensure seamless user experiences.',
  },
  {
    id: '2',
    title: 'Social Media Manager',
    company: 'Big Kahuna Burger Ltd.',
    type: 'On-Site',
    salary: '$400-$1000',
    logo: '/src/assets/Product.svg',
    description: 'Manage social media accounts, create engaging content, and analyze performance metrics to grow brand presence online.',
  },
  {
    id: '3',
    title: 'Graphic Designer',
    company: 'Bitfco Enterprises Ltd.',
    type: 'Remote',
    salary: '$200-$800',
    logo: '/src/assets/Frontend.svg',
    description: 'Create visual concepts using graphic design tools to communicate ideas that inspire, inform, and captivate consumers.',
  },
  {
    id: '4',
    title: 'Sales Executive',
    company: 'Acme Co.',
    type: 'Hybrid',
    salary: '$300-$800',
    logo: '/src/assets/Linked.svg',
    description: 'Identify new business opportunities, build client relationships, and achieve sales targets.',
  },
  {
    id: '5',
    title: 'Frontend Developer',
    company: 'Binford Ltd.',
    type: 'Remote',
    salary: '$500-$1200',
    logo: '/src/assets/Data.svg',
    description: 'Develop and maintain user-facing features using HTML, CSS, and JavaScript frameworks like React or Angular.',
  },
  {
    id: '6',
    title: 'Backend Developer',
    company: 'Code Masters Ltd.',
    type: 'Remote',
    salary: '$600-$1500',
    logo: '/src/assets/Ui.svg',
    description: 'Build and maintain server-side logic, databases, and APIs to ensure high performance and responsiveness.',
  },
  {
    id: '7',
    title: 'Data Analyst',
    company: 'Data Insights Co.',
    type: 'On-Site',
    salary: '$400-$1000',
    logo: '/src/assets/Sales.svg',
    description: 'Analyze data to identify trends, create reports, and provide actionable insights to stakeholders.',
  },
  {
    id: '8',
    title: 'Product Manager',
    company: 'Innovate Corp.',
    type: 'Remote',
    salary: '$800-$2000',
    logo: '/src/assets/Amazon.svg',
    description: 'Define product vision, collaborate with cross-functional teams, and oversee product development from concept to launch.',
  },
  {
    id: '9',
    title: 'Marketing Specialist',
    company: 'Market Pros Ltd.',
    type: 'On-Site',
    salary: '$400-$1000',
    logo: '/src/assets/Google.svg',
    description: 'Plan and execute marketing campaigns, analyze market trends, and optimize strategies to drive brand awareness.',
  },
  {
    id: '10',
    title: 'Customer Support',
    company: 'Helpful Solutions Inc.',
    type: 'Remote',
    salary: '$300-$700',
    logo: '/src/assets/Digital.svg',
    description: 'Assist customers with inquiries, troubleshoot issues, and provide exceptional service to ensure customer satisfaction.',
  },
  {
    id: '11',
    title: 'DevOps Engineer',
    company: 'Cloud Masters Ltd.',
    type: 'Remote',
    salary: '$700-$1800',
    logo: '/src/assets/Apple.svg',
    description: 'Automate deployment processes, manage cloud infrastructure, and ensure system reliability and scalability.',
  },
  {
    id: '12',
    title: 'QA Engineer',
    company: 'Quality Assurance Inc.',
    type: 'On-Site',
    salary: '$500-$1200',
    logo: '/src/assets/Facebook.svg',
    description: 'Design and execute test cases, identify bugs, and ensure the quality of software products before release.',
  },
];

export default JobList;